name: CI

on:
  pull_request:
    branches: [ opened, synchronize ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          java: 21
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Set up JDK
        uses: actions/setup-java@v4.1.0
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew --info test
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.15.1
        if: always()
        with:
          junit_files: '**/build/test-results/test/TEST-*.xml'
